name: CI
on: push
env:
  MIX_ENV: test
  DEPS_CACHE_VERSION: v1
  ELIXIR_VERSION: 1.14
  ERLANG_VERSION: 25.0
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_DB: sleeky_website_test
          POSTGRES_PASSWORD: sleeky_website
          POSTGRES_USER: sleeky_website
        image: postgres:13-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}
      - name: Fetch Mix cache
        id: mix-cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            !_build/${{ env.MIX_ENV }}/sleeky_website
          key: ${{ runner.os }}-deps-erlang-${{ env.ERLANG_VERSION }}-elixir-${{ env.ELIXIR_VERSION }}-mix-${{ hashFiles('**/mix.lock') }}-${{ env.DEPS_CACHE_VERSION }}
      - name: Get dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Get Sleeky guides
        run: mix guides
      - name: Compile
        run: mix compile
      - name: Credo
        run: mix credo --strict
      - name: Run Tests
        run: mix test
